services:
  redis_bus:
    image: redis:7.2-alpine
    container_name: redis_bus
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - broker_net
      - worker_net
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  central_api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: central_api
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      REDIS_HOST: redis_bus
      REDIS_PORT: "6379"
      TXN_PATH: /app/data/POS_transactions.csv
      PYTHONUNBUFFERED: "1"
    volumes:
      - "./data:/app/data:ro"
    depends_on:
      redis_bus:
        condition: service_healthy
    networks:
      - public_net
      - broker_net
    restart: unless-stopped

  pipeline_worker:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    container_name: pipeline_worker
    environment:
      REDIS_HOST: redis_bus
      REDIS_PORT: "6379"
      DATA_ROOT: /app/data
      PYTHONUNBUFFERED: "1"
    volumes:
      - "./data:/app/data:ro"
    depends_on:
      redis_bus:
        condition: service_healthy
    networks:
      - worker_net
      - broker_net
    restart: unless-stopped

networks:
  public_net:
    driver: bridge
  broker_net:
    driver: bridge
  worker_net:
    driver: bridge

volumes:
  redis_data: